root: traits/
output: output/
seed: whales gonna whale
count: 10000

custom:
  - name: Black People
    count: 500
    path: tiers/Usual/Black People
    uses:
      - 1-background
  - name: Miner
    count: 200
    path: tiers/Usual/Miner
    uses:
      - 1-background
  - name: Women
    count: 900
    path: tiers/Usual/Women
    uses:
      - 1-background
    layers:
      - path: 13-lips
        rarity: 1
      - path: 14-hair
        rarity: 1
  - name: Legendary
    count: 777
    path: tiers/Legendary
    special: true
    counts:
      90s: 54
      China Town: 384
      Egypt Mummy: 48
      Hell: 2
      Hood: 12096
      Matrix: 48
      Ninja School: 270
      Paradise: 18
      Santa Village: 240
      Space: 576
      UAE Desert: 1344
      Wall Street: 15552
      Wild West: 240
      Wizard: 240
    

layers:
  - path: 1-background
    rarity: 1
    overrides:
      bg_15: 0.5
      bg_18: 0.5
      bg_6: 0.7
      bg_7: 0.7
      bg_8: 0.7
      bg_9: 0.7
      bg_10: 0.7
      bg_11: 0.7
      bg_12: 0.7
      bg_13: 0.7
      bg_14: 0.7
  - path: 2-body_belly
    rarity: 1
  - path: 3-body_back
    rarity: 1
    overrides:
      body_back_2: 0.7
      body_back_5: 0.7
  - path: 3.5-clothes
    rarity: 1
  - path: 4-eye
    rarity: 1
    overrides:
      eye_5: 0.5
      eye_7: 0.5
  - path: 5-neck
    rarity: 0.5
    overrides:
      '1':
        cannot_be_with:
          - 11-habits/tobacco_pipe
      '2':
        cannot_be_with:
          - 11-habits/tobacco_pipe
      '3':
        cannot_be_with:
          - 11-habits/tobacco_pipe
      '4':
        cannot_be_with:
          - 11-habits/tobacco_pipe
  - path: 6-tooth
    rarity: 0.6
    cannot_be_with:
      - 11-habits
  - path: 7-glasses
    rarity: 0.4
    overrides:
      black:
        cannot_be_with:
          - 4-eye
      rainbow:
        cannot_be_with:
          - 4-eye

  - path: 8-tale
    rarity: 0.35
    overrides:
      '14': 0.7
  - path: 9-hand
    rarity: 0.1
  - path: 10-hats
    rarity: 0.7
    overrides:
      '4':
        cannot_be_with:
          - 7-glasses
          - 3-body_back/body_back_3
          - 3-body_back/body_back_5
          - 3-body_back/body_back_6
      '6':
        cannot_be_with:
          - 7-glasses
      '12':
        cannot_be_with:
          - 7-glasses
      '13':
        cannot_be_with:
          - 7-glasses
      '14':
        cannot_be_with:
          - 7-glasses
      '15':
        cannot_be_with:
          - 7-glasses
      '18':
        cannot_be_with:
          - 7-glasses
      '20':
        cannot_be_with:
          - 7-glasses
      '21':
        cannot_be_with:
          - 7-glasses

  - path: 11-habits
    rarity: 0.2
    cannot_be_with:
      - 6-tooth

  - path: 12-flags
    rarity: 0.05
    cannot_be_with:
      - 9-hand
